### PR TITLE
Testing tiles

### PR DESCRIPTION
**Pull request by LarsFin**
Made some changes to the Tile class and made tests for class methods. 

Issues resolved with pull request; #11 (tiles have capacity)

### CODE REVIEW

**Comment by LarsFin** [comment]
Issue #13 now also completed

**Comment by LarsFin** [comment]
Covered: Issue #8 // commit 8cbe87e

**Comment by Le5tes** [comment]
Awesome. My only comment is that I think the testing suite has an 'includes' matcher that you could have used.

**Comment by LarsFin** [comment]
Your right;
```
Expect.prototype.toContain = function(parameter) {
  this.message = `to contain ${parameter}`
  this.result = this.parameter.includes(parameter)
  return this
}
```
I'll change that now.
Thankyou for reviewing my code

**Pull request merged**
